source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'StasDiary' do
  use_frameworks!

  # Pods for StasDiary
  pod 'SearchTextField', '~> 1.2.2'
  pod 'Charts'
  #pod 'Alamofire', '~> 5.0.0.beta.1'

end
